AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*
    - vendor/**/*
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/BracesAroundHashParameters:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Max: 130
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  StyleGuide: '#120-character-limits'
  Enabled: true
  Max: 120

Style/Documentation:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/SymbolArray:
  EnforcedStyle: brackets

Style/AndOr:
  EnforcedStyle: conditionals

Rails/HttpStatus:
  EnforcedStyle: numeric

Rails/DynamicFindBy:
  Enabled: false
