
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: point_of_sale_development

test:
  <<: *default
  database: point_of_sale_test

production:
  <<: *default
  database: point_of_sale_production

staging:
  <<: *default
  database: point_of_sale_staging
